[workspace]
resolver = "2"
members = [
    "crates/meuxe-mm",
    "crates/meuxe-abi",
    "crates/meuxe-cap",
    "crates/meuxe-elf",
    "crates/meuxe-fs",
    "crates/meuxe-font",
    "crates/meuxe-logo",
    "crates/meuxe-netstack",
    "crates/meuxe-ui",
    "servers/meuxe-rt",
    "servers/meuxe-vfs",
    "servers/meuxe-blk",
    "servers/meuxe-compositor",
    "servers/meuxe-client",
    "servers/meuxe-files",
    "servers/meuxe-calc",
    "servers/meuxe-input",
    "servers/meuxe-hello",
    "servers/meuxe-fault",
    "servers/meuxe-net",
    "kernel",
]

[profile.release]
opt-level = 2
lto = false
codegen-units = 1
debug = 1
