[package]
name = "meuxe-vfs"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
description = "Meuxe VFS server"

[[bin]]
name = "meuxe-vfs"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
meuxe-abi = { path = "../../crates/meuxe-abi" }
meuxe-fs = { path = "../../crates/meuxe-fs" }
meuxe-rt = { path = "../meuxe-rt" }
