[package]
name = "meuxe-fault"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[[bin]]
name = "meuxe-fault"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
meuxe-abi = { path = "../../crates/meuxe-abi" }
meuxe-rt = { path = "../meuxe-rt" }
